name: Clean up build artifacts
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 24 hours
        uses: glassechidna/artifact-cleaner@master
        with:
          minimumAge: 86400